### PR TITLE
Done with Issue #92

### PR DESCRIPTION
**Pull request by OpariucRares**
Done with this issue

### CODE REVIEW

**Comment by baranceanuvlad** [comment]
Comentariu

**Review by Glowpride — COMMENTED** [review]
Wa da fuck happened here? dc asa multe change-uri?

**Comment by OpariucRares** [comment]
A fost o problema la pull si a trebuit sa scot folderul de Backend, sa fac commit fara folder si dupa sa il adaug.

**Review by baranceanuvlad — COMMENTED** [review]
Mi-a placut sa fac review

**Review by Glowpride — CHANGES_REQUESTED** [review]
Am schimbat sa poata da approve oricine dar tot nu inteleg ce e cu oala asta de sarmale... problema e din cauza ca inainte folderul era BackEnd si acuma l-ai facut Backend... rezolva asta si mai vedem

**Comment by Al-Andrew** [comment]
By the way: 'Done with Issue #92' is not going to be an acceptable title from now on.... the title of the pull request should be more descriptive of what was actually done

**Comment by OpariucRares** [comment]
The issue explains it

**Review by Al-Andrew — APPROVED** [review]
Now all seems fine

**Review by cristiancibotariu — APPROVED** [review]

**Pull request merged**
